#!/usr/bin/env python2

#FIXME testing only, don't use this

from subprocess import Popen
from sys import exit
import time

blockify = Popen(["blockify.py"])
time.sleep(2)

def cleanup():
    Popen(['amixer', '-q', 'set', 'Master', 'unmute'])
    print "Cleaned up"
    exit(0)
    

while True:
    alive = blockify.poll()
    if alive is None:
        pass
    else:
        cleanup()
    time.sleep(1)
